config/routes.rb
Rails.application.routes.draw do
    namespace :admin do
      resources :users
      resources :doctors
      resources :appointments
      resources :categories
      resources :prescriptions
      resources :admin_users

      root to: 'admin_users#index'
    end


  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }


  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations',
  }

  authenticated :user do
    root 'users#index', as: :authenticated_user_root
  end

  authenticated :doctor do
    root 'doctors#index', as: :authenticated_doctor_root
  end

  authenticated :admin_user do
    root 'admin/admin_users#index', as: :authenticated_admin_user_root
  end

  resources :users
  resources :doctors
  resources :appointments
  resources :prescriptions
  #resources :admin_users


  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  # Defines the root path route ("/")


  root "home#index"
end

app/models/prescription.rb
class Prescription < ApplicationRecord
	belongs_to :appointment
	
	validates :prescript, presence: true, length: { in: 1..1000 }
end

app/controllers/admin/prescriptions_controller.rb
module Admin
  class PrescriptionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :authenticate_doctor!, only: %i[create destroy]

  def index
    @user = current_doctor
    @appointments = @user.appointments
    appointment_ids = @appointments.map(&:id)
    @prescription = Prescription.where(appointment_ids: appointment_ids)
  end

  def show
    @user = current_doctor
    @prescription = Prescription.find(params[:id])
    @appointment = Appointment.find(@prescription.appointment_id)
  end

  def new
    @user = current_doctor
    @appointment = Appointment.find_by(id: params[:appointment_id])
    @prescription = Prescription.new
  end

  def create
    @user = current_doctor
    @appointment = Appointment.find_by(id: params[:appointment_id])
    @prescription = Prescription.new(prescription_params)

    if @prescription.save
      redirect_to prescriptions_path
      flash[:notice] = 'Your prescription was successfully created'
    else
      render :new, alert: 'An error has occurred while creating a prescription'
    end
  end

  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy!
    redirect_to prescriptions_path(current_doctor.id), notice: 'Recommendation was deleted'
  end

  private

  def prescription_params
    params.require(:prescription).permit(:prescript, :appointment_id)
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/index.html.erb
<%= link_to 'Back', doctor_path(@user.id), class: "btn btn-primary btn-lg" %>

<h1 class="display-3 text-center main-title mt-4">All prescriptions</h1>

<div class="row card-body mt-4">
  <div class="col-md-12">
    <% if @appointments.blank? %>
      <h4 class="font-italic">You don't have any appointment</h4>
    <% else %>
      <h2 class="font-italic">Your appointment</h2>
      <div class="d-flex gap-3 flex-wrap mt-5">
        <% @appointments.each do |appointment| %>
          <div class="card p-2">
            <div class="card-body">
              <% if appointment.prescription.blank? %>
                <span class="text-danger">Empty prescription</span>
                <%= ' ' %>
              <% else %>
                <h4><span class="text-primary">Prescription for:</span>
                  <strong><%= appointment.user.full_name %></strong></h4>
                <p><%= appointment.prescription.prescript %></p>
              <% end %>
            </div>
          </div>
        <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/prescriptions/new.html.erb
<%= link_to 'Back', doctor_path(@user.id), class: "btn btn-primary btn-lg" %>

<section>
  <h1 class="display-3 text-center">Add a new prescription</h1>
  <h2 class="font-italic">Prescript</h2>
  <p class="font-italic p-4 alert-warning">Write your prescript for patient:
    <strong><%= @appointment.user.full_name %></strong></p>
  <%= form_with model: @prescription, url: prescriptions_path, class: "left" do |f| %>
    <%= f.hidden_field :appointment_id, value: @appointment.id %>  <br>
    <%= f.text_area :prescript, cols: 30, rows: 10, class: 'form-control', id: 'Prescript' %> <br>
    <%= f.submit "Submit", class: 'btn btn-primary btn-lg ' %>
  <% end %>
</section>

app/views/prescriptions/show.html.erb
<% if current_user %>
  <%= link_to 'Back', user_path(@user.id), class: "btn btn-primary btn-lg" %>
<% else %>
  <%= link_to 'Back', doctor_path(@user.id), class: "btn btn-primary btn-lg" %>
<% end %>

<h1 class="display-3 text-center mt-4">Your Prescription</h1>
<div class="row card-body mt-4">
  <div class="col-md-7">
    <h5>Recommendation from doctor: <strong><%= @appointment.doctor.full_name %></strong></h5>
    <p><%= @prescription.prescript %></p>
    <% if current_doctor %>
      <div>
        <%= button_to "Delete this recommendation", @prescription, 'method': :delete, class: 'btn btn-danger text-light rounded-2 my-2' %>
      </div>
    <% end %>
  </div>
</div>