config/routes.rb
Rails.application.routes.draw do
    namespace :admin do
      resources :users
      resources :doctors
      resources :appointments
      resources :categories
      resources :prescriptions
      resources :admin_users

      root to: 'admin_users#index'
    end


  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }


  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations',
  }

  authenticated :user do
    root 'users#index', as: :authenticated_user_root
  end

  authenticated :doctor do
    root 'doctors#index', as: :authenticated_doctor_root
  end

  authenticated :admin_user do
    root 'admin/admin_users#index', as: :authenticated_admin_user_root
  end

  resources :users
  resources :doctors
  resources :appointments
  resources :prescriptions
  #resources :admin_users


  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  # Defines the root path route ("/")


  root "home#index"
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
      %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br/>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %>
    <br/>
  <% end %>
<% end %>

app/views/shared/_logout_file.html.erb
<ul class="navbar-nav mt-5 text-right">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to('Logout', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-primary btn-lg') %>

    </li>
  <% elsif admin_user_signed_in? %>
    <li class="nav-item">
      <%= link_to('Logout', destroy_admin_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-primary btn-lg') %>
    </li>
  <% elsif doctor_signed_in? %>
    <li class="nav-item">
      <%= link_to('Logout', destroy_doctor_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-primary btn-lg') %>
    </li>
  <% end %>
</ul>