config/routes.rb
Rails.application.routes.draw do
    namespace :admin do
      resources :users
      resources :doctors
      resources :appointments
      resources :categories
      resources :prescriptions
      resources :admin_users

      root to: 'admin_users#index'
    end


  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }


  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations',
  }

  authenticated :user do
    root 'users#index', as: :authenticated_user_root
  end

  authenticated :doctor do
    root 'doctors#index', as: :authenticated_doctor_root
  end

  authenticated :admin_user do
    root 'admin/admin_users#index', as: :authenticated_admin_user_root
  end

  resources :users
  resources :doctors
  resources :appointments
  resources :prescriptions
  #resources :admin_users


  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  # Defines the root path route ("/")


  root "home#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence: true
  validates :phone, presence: true
  validates :phone, numericality: {only_integer: true}
  validates :phone, length: {is: 10}
  
  belongs_to :category
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_one_attached :attachment
  
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/admin/doctors_controller.rb
module Admin
  class DoctorsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/doctors/confirmations_controller.rb
# frozen_string_literal: true

class Doctors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/doctors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Doctors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/doctors/passwords_controller.rb
# frozen_string_literal: true

class Doctors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true

class Doctors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors/sessions_controller.rb
# frozen_string_literal: true

class Doctors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/doctors/unlocks_controller.rb
# frozen_string_literal: true

class Doctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
before_action :set_doctor_item, only: %i[update]
  before_action :authenticate_doctor!
  
  def index
    @doctor = current_doctor
  end

  def show
    @appointments = Appointment.where(doctor_id: current_doctor.id)
    @prescriptions = Prescription.where(appointments_id: current_doctor.id)
  end

  def new
    @doctor = Doctor.new
  end

  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_path, notice: 'The photo added to your profile' }
      else
        format.html { render :index }
      end
    end
  end

  private

  def doctor_params
    params.require(:doctor).permit(:main_image)
  end

  def set_doctor_item
    @doctor = Doctor.find(params[:id])
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/index.html.erb
<h1 class="display-3 text-center main-title mt-4">Doctors public page</h1>

<%= render '/shared/logout_file' %>

<div class="row featurette card-body mt-4">
  <div class="col-md-7">
    <h2 class="featurette-heading">Hello dear <%= current_doctor.full_name %></h2>
    <p class="lead">For more than 100 years, Our Medical Center has been driven by a commitment to care for all people,
      regardless of their ability to pay, providing not only traditional medical care, but also programs and services
      that wrap around that care to enhance overall health. All of this supports our mission to provide exceptional
      care, without exception. </p>
    <div class="custom-btn-image">
      <%= link_to "Enter your profile", doctor_path(@doctor), class: "btn btn-success btn-lg text-white" %>
    </div>
  </div>
  
</div>

app/views/doctors/show.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="display-3">Doctor's profile</h1>
      <h2>Dear doctor <%= current_doctor.full_name %>!</h2>
      <h3 class="text-primary"> <%= current_doctor.category&.name %> </h3>
      <p class="lead">Work please with opened appointments</p>
      <p>
        <%= link_to('Back', root_path, class: 'btn btn-secondary my-2') %>
        <%= link_to('Prescriptions', prescriptions_path, class: 'btn btn-primary') %>
      </p>
    </div>
  </section>

  <div class="container">
    <div class="row featurette card-body mb-4">
      <div class="col-md-12">
        <h1 class="text-center mb-4">All appointments</h1>
        <% if @appointments.blank? %>
          <h4 class="font-italic">You don't have any appointment</h4>
        <% else %>
          <div class="album py-5 bg-light">
            <div class="container">
              <div class="row">
                <% @appointments.each do |appointment| %>
                  <% if appointment.prescription %>
                    <div class="col-md-4">
                      <div class="card mb-4 box-shadow">
                        <div class="card-body">
                          <h4 class="mx-1"><strong>Prescription</strong></h4>
                          <p class="pt-3"><strong>Appointment Status: </strong>
                            <strong class="text-danger">Closed</strong></p>
                          <p class="card-text"><strong>User: </strong> <%= appointment.user.full_name %></p>
                          <p class="card-text">
                            <strong>Appointment date: </strong> <%= appointment.appointment_date&.to_s(:long) %></p>
                          <%= link_to('Edit', prescription_path(appointment.prescription.id), class: 'btn btn-outline-secondary my-2') %>
                          <br>
                          <small class="font-italic text-grey"><%= distance_of_time_in_words(appointment.created_at, Time.now) %>
                            ago
                          </small>

                        </div>
                      </div>
                    </div>
                  <% else %>
                    <div class="col-md-4">
                      <div class="card mb-4 box-shadow">
                        <div class="card-body">
                          <h4 class="mx-1"><strong>Prescription</strong></h4>
                          <p class="mt-4"><span>Appointment Status:</span> <strong class="text-primary">Opened</strong>
                          </p>
                          <p class="card-text"><span>User:</span> <%= appointment.user.full_name %></p>
                          <p class="card-text">
                            <span>Appointment date:</span> <%= appointment.appointment_date&.to_s(:long) %></p>
                          <%= link_to('Create', new_prescription_path(appointment_id: appointment.id), class: 'btn btn-primary my-2') %>
                          <br>
                          <small class="font-italic text-grey"><%= distance_of_time_in_words(appointment.created_at, Time.now) %>
                            ago
                          </small>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>